- name: Add antidote commands if not present
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    state: present
  loop:
    - "source ${ZDOTDIR:-~}/.antidote/antidote.zsh"
    - "antidote load"
  tags: &tags_for_zsh_tasks ['install','productivity','dotfiles','zsh']

- name: Install starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  tags: *tags_for_zsh_tasks
    
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

#- name: Installazione di GPG (se non già presente)
#  become: yes
#  apt:
#    name: gnupg
#    state: present
#    update_cache: yes
#  tags: *tags_for_zsh_tasks
#- name: Crea directory per le chiavi APT
#  become: yes
#  file:
#    path: /etc/apt/keyrings
#    state: directory
#    mode: '0755'
#  tags: *tags_for_zsh_tasks
#
#- name: Scarica la chiave GPG per il repository e converti in formato binario
#  become: yes
#  ansible.builtin.command: 
#    cmd: "wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --dearmor -o /etc/apt/keyrings/gierens.gpg"
#  args:
#    creates: /etc/apt/keyrings/gierens.gpg
#  tags: *tags_for_zsh_tasks
#
#- name: Aggiungi repository per eza se non presente
#  become: yes
#  ansible.builtin.lineinfile:
#    path: /etc/apt/sources.list.d/gierens.list
#    line: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"
#    create: yes
#    state: present
#  tags: *tags_for_zsh_tasks
#
#- name: Imposta permessi per i file di configurazione
#  become: yes
#  file:
#    path: "{{ item }}"
#    mode: '0644'
#  loop:
#    - /etc/apt/keyrings/gierens.gpg
#    - /etc/apt/sources.list.d/gierens.list
#  tags: *tags_for_zsh_tasks
#
#- name: Aggiorna l'elenco dei pacchetti, ignorando repository non sicuri
#  become: yes
#    ansible.builtin.command:
#      cmd: apt-get update --allow-insecure-repositories
#  tags: *tags_for_zsh_tasks
#
#- name: Installa eza
#  become: yes
#  apt:
#    name: eza
#    state: present
#  tags: *tags_for_zsh_tasks
